### PR TITLE
Minor issues

### PR DESCRIPTION
**Pull request by adius**
Hi,

there were some typos and bugs in your code.
I took the liberty to fix them for you. 😉

Well, actually, [Feram] did it.
It’s a tool that we developed to fix our own code.
If you want to use it as well, it’s really simple to integrate:
[feram.io/help/getting-started]

Hope you like it! 😁

[Feram]: http://feram.io
[feram.io/help/getting-started]: https://feram.io/help/getting-started

### CODE REVIEW

**Comment by DrPaulBrewer** [comment]
Adius: thanks for the PR.   Unfortunately the PR was inconsistent and mostly stylistic, so I am unable
to accept it.  

Change one `function` to `()=>` and leaving the rest be is inconsistent. 

I realize you are advertising an automated service.  Since the point of marketing is usually to maximize
new customers or customer impressions, and the point of fixing bugs, is fixing actual incorrect code
and vulnerabilities, there may be some conflict between these goals.  You might get higher value per
customer with the latter, but it will be more work.

Good luck,

Paul

**Comment by adius** [comment]
Hey Paul,

thanks for your feedback! Actually this PR only contains a subset of the issues Feram was able to detect. I'm rewriting the PR message today so this gets clearer. If you wanted to see all the fixes you'd have to activate Feram via https://github.com/apps/feram.

To be honest, we're having a hard time finding customers at the moment. So it would be great to hear your general opinion on the product. Are we heading in the right direction or should we rather build something else? 😅

Thanks for your help!

**Comment by DrPaulBrewer** [comment]
Adius:

I don't know if this really answers your questions but I hope it helps.

It is a tough sell to patch together a bunch of tools that "find" code defects and suggest that someone
subscribe (even for free) to its suggestions for improvement, when their code is working and their tests are passing and they are mostly happy with it.  The possibility of noise is pretty high,
even with focused products.  Trust is important, and it easy to ask for too much trust too soon.  A product called snyk wanted me to accept PRs to reduce security vulnerabilities.  That sounds like a good idea.  But the name, snyk, is a lot like sneak. What do they want to sneak into my code?  It could be correct 99% of the time, but the 1 time it is wrong or compromised is a problem.  Perhaps a better solution 
than for me to fix it with stranger's automated PR, is to automate filing issues with the person in charge of an identified library that contains poor code or send them PR to fix vulnerability upstream, then when fixed announce downstream.  These notices could include things like "did you know 327 other projects
depend on your code? here's a list.  They would really love it if you fixed your string overflow vulnerability as detailed in CERT-12345667 issued 01/14/2007 link.  

If you had a tool that could find github projects with BUILD FAILING and suggest patches that are known to cause the builds to pass, that would be more impressive.  

Greenkeeper.io does automated external change-compatibility testing and while being more focused still manages to produce a little too much information at times.

As you know, most code depends on other code imported from libraries.  Changes in other peoples' code can cause bugs in code that relies on stable behavior.  In node.js, at least, the dependencies are obvious because they are listed in the package.json file and are usually also explicit in `require` statements.  Other languages have their own way of importing external code.  Greenkeeper monitors all of the dependencies of a customer's code for new versions,  When a new version is released, it is tested against all of the customer's related code and issues and/or PRs are generated.   This is pretty useful for enhancing awareness of how often something changes, and whether the new version seems to be compatible.  In this way it warns me when something might be broken or become broken, or that it is now fixed upstream.

**Comment by adius** [comment]
Thanks a lot for the extensive feedback!

> when their code is working and their tests are passing and they are mostly happy with it

Yeah, I guess many people feel too confident about their code, but especially scripting languages are mine fields. You can never be sure, but it's hard to raise this awareness 😕.

I'm not sure if this clear, but Feram does not create pull requests in the first place. We create a list of fixes and present them to the developer on a feram.io subpage. Only the ones they approve are then bundled in a pull request.
But yeah, the trust issue still stands, as we need to read their code. That's actually an interesting point. Thanks for pointing it out. I guess we could also a service to first check 3rd party tools. So one can get familiar with Feram without having to provide their code.

At the moment we already include https://github.com/presidentbeef/brakeman, which gives security warnings about ruby dependencies. The next days we also going to enable retire.js, which warns about vulnerable npm packages.

**Comment by adius** [comment]
Including dynamic checks would be our next big upgrade, but this is going to be hard if you want to do it automatically (This is kind of our mantra. We don't want to have to generate a config file first to use a service). I mean the big question is: Is Feram's success dependent on how many/good fixing tools we provide, or is the idea/process conceptually flawed?

**Pull request closed without merging**
